#!/usr/bin/env ts-node

const algorithms = {

  brotli() {
    const compress = require('iltorb').compressStream({
      mode:      1 /*UTF-8 formatted text input*/,
      quality:   11 /*max*/,
      lgwin:     24 /*max*/,
      lgblock:   24 /*max*/,
      size_hint: require('fs').fstatSync(process.stdin.fd).size,
    });
    process.stdin
      .pipe(compress)
      .pipe(process.stdout);
  },

};


const algorithm = algorithms[process.argv[2]];
if (typeof algorithm === 'function') {
  algorithm();
} else {
  throw new Error("Unsupported algorithm: " + algorithm);
}
