#!/usr/bin/env ts-node --pretty --files

const JSONStream = require('JSONStream');

const algorithms = {

  "sql"(){
    const XmlToSQLTransform = require('./src/XmlToSQLTransform').default;
    process.stdin
    .pipe(new XmlToSQLTransform())
    .pipe(process.stdout);
  },

  "6NF.json"(){
    const XmlTo6NFTransform = require('./src/XmlTo6NFTransform').default;
    process.stdin
    .pipe(new XmlTo6NFTransform())
    .pipe(JSONStream.stringify(false))
    .pipe(process.stdout);
  },

};



const algorithm = algorithms[process.argv[2]];
if (typeof algorithm === 'function') {
  algorithm();
} else {
  throw new Error("Unsupported algorithm: " + algorithm);
}


